/**
 * Centralized i18n strings for bilingual (zh/en) report generation.
 */

export type Lang = "zh" | "en";

/** Get a bilingual string by language key. */
function t(zh: string, en: string): Record<Lang, string> {
  return { zh, en };
}

// ---------------------------------------------------------------------------
// Status & error messages (used in index.ts, rollup.ts)
// ---------------------------------------------------------------------------

export const MSG = {
  noData: t("⚠️ 数据获取失败，无法生成报告。", "⚠️ Data unavailable, unable to generate report."),
  summaryFailed: t("⚠️ 摘要生成失败。", "⚠️ Summary generation failed."),
} as const;

// ---------------------------------------------------------------------------
// Report headers & labels
// ---------------------------------------------------------------------------

export const DOUYIN_REPORT = {
  title: t("抖音热搜日报", "Douyin Hot Search Digest"),
  issueTitle: (dateStr: string, lang: Lang) =>
    lang === "en" ? `🔥 Douyin Hot Search Digest ${dateStr}` : `🔥 抖音热搜日报 ${dateStr}`,
} as const;

export const BILI_REPORT = {
  title: t("B站热门视频日报", "Bilibili Trending Videos Digest"),
  issueTitle: (dateStr: string, lang: Lang) =>
    lang === "en" ? `📺 Bilibili Trending Videos ${dateStr}` : `📺 B站热门视频日报 ${dateStr}`,
} as const;

export const BILI_MUSIC_REPORT = {
  title: t("B站热门音乐日报", "Bilibili Trending Music Digest"),
  issueTitle: (dateStr: string, lang: Lang) =>
    lang === "en" ? `🎵 Bilibili Trending Music ${dateStr}` : `🎵 B站热门音乐日报 ${dateStr}`,
} as const;

export const WEEKLY_REPORT = {
  title: t("短视频热点周报", "Short-Video Trends Weekly Report"),
  coverage: t("覆盖日期", "Coverage"),
  issueTitle: (weekStr: string) => `📅 短视频热点周报 ${weekStr}`,
} as const;

export const MONTHLY_REPORT = {
  title: t("短视频热点月报", "Short-Video Trends Monthly Report"),
  issueTitle: (monthStr: string) => `📆 短视频热点月报 ${monthStr}`,
} as const;

export const ISSUE_LABELS: Record<string, Record<Lang, string>> = {
  douyin: t("douyin", "douyin-en"),
  bili: t("bili", "bili-en"),
  "bili-music": t("bili-music", "bili-music-en"),
  weekly: t("weekly", "weekly-en"),
  monthly: t("monthly", "monthly-en"),
};

/**
 * Map a source id (from config.yml) to its i18n report metadata.
 * Used by report-savers.ts and index.ts to be fully config-driven.
 */
import type { HotSource } from "./config.ts";

interface ReportMeta {
  title: Record<Lang, string>;
  issueTitle: (dateStr: string, lang: Lang) => string;
}

const REPORT_META_BY_ID: Record<string, ReportMeta> = {
  douyin: DOUYIN_REPORT,
  bili: BILI_REPORT,
  "bili-music": BILI_MUSIC_REPORT,
};

/** Fallback meta for sources not in the built-in map (uses source.name). */
function fallbackMeta(source: HotSource): ReportMeta {
  return {
    title: t(`${source.name}日报`, `${source.name} Digest`),
    issueTitle: (dateStr: string, lang: Lang) =>
      lang === "en" ? `📊 ${source.name} Digest ${dateStr}` : `📊 ${source.name}日报 ${dateStr}`,
  };
}

export function getReportMeta(source: HotSource): ReportMeta {
  return REPORT_META_BY_ID[source.id] ?? fallbackMeta(source);
}

// ---------------------------------------------------------------------------
// Footer (used in report.ts)
// ---------------------------------------------------------------------------

export const FOOTER = {
  autoGen: t("本日报由", "This digest is auto-generated by"),
} as const;

// ---------------------------------------------------------------------------
// Report labels for manifest/RSS (used in generate-manifest.ts)
// ---------------------------------------------------------------------------

export const REPORT_LABELS: Record<string, string> = {
  "ai-douyin": "抖音热搜日报",
  "ai-douyin-en": "Douyin Hot Search Digest",
  "ai-bili": "B站热门视频日报",
  "ai-bili-en": "Bilibili Trending Videos Digest",
  "ai-bili-music": "B站热门音乐日报",
  "ai-bili-music-en": "Bilibili Trending Music Digest",
  "ai-weekly": "短视频热点周报",
  "ai-weekly-en": "Short-Video Trends Weekly Digest",
  "ai-monthly": "短视频热点月报",
  "ai-monthly-en": "Short-Video Trends Monthly Digest",
};

// ---------------------------------------------------------------------------
// Telegram / Feishu notification labels (used in notify.ts / feishu.ts)
// ---------------------------------------------------------------------------

export const NOTIFY_LABELS: Record<string, Record<Lang, string>> = {
  "ai-douyin": t("抖音热搜", "Douyin Hot"),
  "ai-bili": t("B站热门", "Bilibili Trending"),
  "ai-bili-music": t("B站音乐", "Bilibili Music"),
  "ai-weekly": t("短视频热点周报", "Weekly Digest"),
  "ai-monthly": t("短视频热点月报", "Monthly Digest"),
};
